name: GHA Workshop

on:
  push:
    branches:
      - main
  # Exercise: Try adding a trigger for pull requests!
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Report Status
        if: always()
        run: |
          echo "Tests completed with status: ${{ job.status }}"
      lint:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v3

          - name: Setup Node.js
            uses: actions/setup-node@v3

  # Exercise: Add a new job to lint the app here!
  # Hint: You can use the same runner as the test job
